server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5431}/${DATABASE_NAME:postgres?currentSchema=basqaru}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:12345}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update